=== edusawabe/JavaProjects/CobolParserFXML/Teste.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="Root">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element minOccurs="0" maxOccurs="100" name="item">
          <xsd:complexType>
            <xsd:all>
              <xsd:element minOccurs="0" maxOccurs="1" name="NomeComponente" />
              <xsd:element name="DataAlteracao" minOccurs="0" maxOccurs="1">
</xsd:element><xsd:element minOccurs="0" maxOccurs="1" name="AlterouPDC" />
              <xsd:element minOccurs="0" maxOccurs="1" name="BookEntradaAlterado" />
              <xsd:element minOccurs="0" maxOccurs="1" name="BookSaidaAlterado" />
              <xsd:element minOccurs="0" maxOccurs="1" name="FluxoPDCAlterado" />
              <xsd:element minOccurs="0" maxOccurs="1" name="PacoteChangeman" />
              <xsd:element minOccurs="0" maxOccurs="1" name="Demanda" /><xsd:element name="DescricaoAlteracoes" minOccurs="0" maxOccurs="1">
</xsd:element>
              <xsd:element minOccurs="0" maxOccurs="1" name="DataImplantacao" />
            </xsd:all>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== edusawabe/JavaProjects/CobolParserFXML/NewFile1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Teste.xsd">
	<item>
		<NomeComponente>RFIN102F</NomeComponente>
		<AlterouPDC>N達o</AlterouPDC>
		<BookEntradaAlterado>N達o</BookEntradaAlterado>
		<BookSaidaAlterado>N達o</BookSaidaAlterado>
		<FluxoPDCAlterado>N達o</FluxoPDCAlterado>
		<PacoteChangeman>RFIN000487</PacoteChangeman>
		<Demanda>TH</Demanda>
		<DataImplantacao>Proxima</DataImplantacao></item></Root>
